
export enum ModelNames {
    USER="users",
    EMPLOYEES="employees",
    COUNTERS="counters",
    BRANCHES="branches",
    STATES="states",
    DISTRICTS="districts",
    CITIES="cities",
    GENERALS="generals",
    GOLD_RATE_TIMELINES="gold_rate_timelines",
    DELIVERY_HUBS="delivery_hubs",
    GROUP_MASTERS="group_masters",
    CATEGORIES="categories",
    SUB_CATEGORIES="sub_categories",
    STONE="stones",
    PURITY="purities",
    DEPARTMENT="departments",
    PROCESS_MASTER="process_masters",
    UNIT_MASTER="unit_masters",
    TDS_MASTERS="tds_masters",
    TCS_MASTERS="tcs_masters",
    TRANSPORT_MASTERS="transport_masters",
    TEST_CENTER_MASTERS="test_center_masters",
    TEST_CHARGE_MASTERS="test_charge_masters",
    FACTORIES="factories",
    AGENTS="agents",
    SUPPLIERS="suppliers",
    COMPANIES="companies",
    GLOBAL_GALLERY_CATEGORIES="global_gallery_categories",
    BANKS="banks",
    GLOBAL_GALLERIES="global_galleries",
   
    

}