export enum ModelNames {
  USER = 'users',
  EMPLOYEES = 'employees',
  COUNTERS = 'counters',
  BRANCHES = 'branches',
  STATES = 'states',
  DISTRICTS = 'districts',
  CITIES = 'cities',
  GENERALS = 'generals',
  GOLD_RATE_TIMELINES = 'gold_rate_timelines',
  DELIVERY_HUBS = 'delivery_hubs',
  GROUP_MASTERS = 'group_masters',
  CATEGORIES = 'categories',
  SUB_CATEGORIES = 'sub_categories',
  STONE = 'stones',
  PURITY = 'purities',
  DEPARTMENT = 'departments',
  PROCESS_MASTER = 'process_masters',
  UNIT_MASTER = 'unit_masters',
  TDS_MASTERS = 'tds_masters',
  TCS_MASTERS = 'tcs_masters',
  LOGISTICS_PARTNERS = 'logistics_partners',
  TEST_CENTER_MASTERS = 'test_center_masters',
  TEST_CHARGE_MASTERS = 'test_charge_masters',
  TEST_CHARGE_ITEMS_MASTERS = 'test_charge_items_masters',
  FACTORIES = 'factories',
  AGENTS = 'agents',
  SUPPLIERS = 'suppliers',
  COMPANIES = 'companies',
  GLOBAL_GALLERY_CATEGORIES = 'global_gallery_categories',
  BANKS = 'banks',
  GLOBAL_GALLERIES = 'global_galleries',
  RATE_CARDS = 'rate_cards',
  RATE_CARD_PERCENTAGESS = 'rate_card_percentages',
  RATE_BASE_MASTERS = 'rate_base_masters',
  SHOPS = 'shops',
  ORDER_SALES_MAIN = 'order_sales',
  ORDER_SALES_ITEMS = 'order_sales_items',
  ROOT_CAUSES = 'root_causes',
  ORDER_SALES_DOCUMENTS = 'order_sales_documents',
  SUB_PROCESS_MASTER = 'sub_process_masters',
  ORDER_SALE_HISTORIES = 'order_sale_histories',
  ORDER_SALE_SET_PROCESSES = 'order_sale_set_processes',
  ORDER_SALE_SET_SUB_PROCESSES = 'order_sale_set_sub_processes',
  ORDER_SALE_SET_PROCESS_HISTORIES = 'order_sale_set_process_histories',
  ORDER_SALE_SET_SUB_PROCESS_HISTORIES = 'order_sale_set_sub_process_histories',
  PRODUCTS = 'products',
  PRODUCT_STONE_LINKIGS = 'product_stone_linkings',
  PRODUCT_DOCUMENTS_LINKIGS = 'product_documents_linkings',
  COLOUR_MASTERS = 'colour_masters',
  STONE_COLOUR_LINKINGS = 'stone_colour_linkings',
  USER_ATTENDANCES = 'user_attendaces',
  HALMARK_CENTERS = 'halmark_centers',
  HALMARKING_REQUESTS = 'halmarking_requests',
  CUSTOMERS = 'customers',
  DELIVERY_PROVIDER = 'delivery_providers',
  PHOTOGRAPHER_REQUESTS = 'photographer_requests',
  DELIVERY_CHALLANS = 'delivery_challans',
  DELIVERY_CHALLAN_ITEMS = 'delivery_challan_items',
  INVOICES = 'invoices',
  INVOICE_ITEMS = 'invoice_items',
  FACTORY_CALCULATION_TYPE_MASTER = 'factory_calculation_type_masters',
  FACTORY_CALCULATION_TYPE_MASTER_ITEMS = 'factory_calculation_type_master_items',
  GOLD_TESTING_REQUESTS = 'gold_testing_requests',
  GOLD_TESTING_REQUEST_ITEMS = 'gold_testing_request_items',
  DELIVERY_TEMP = 'delivery_temps',
  DELIVERY = 'deliveries',
  DELIVERY_ITEMS = 'delivery_items',
  DELIVERY_REJECTED_PENDINGS = 'delivery_rejected_pendings',
  DELIVERY_RETURN = 'delivery_returns',
  DELIVERY_RETURN_ITEMS = 'delivery_return_items',
  OTP = 'otps',
  DELIVERY_COUNTERS = 'delivery_counters',

  CHAT_PERSONAL_CHAT_MESSAGES = 'chat_personal_chat_messages',
  CHAT_PERSONAL_CHATS = 'chat_personal_chats',
  CHAT_PENDING_MESSAGES = 'chat_pending_messages',






  
  
}
